### ISSUE TITLE
Client doesn't properly handle ScaleValue attribute

### ISSUE THREAD

**Issue by iagopiimenta** [docusign/docusign-ruby-client#18]
This occurs with `DocuSign_eSign::SignHere` and `DocuSign_eSign::InitialHere` models.

Current behavior:
```ruby
=> DocuSign_eSign::SignHere.new.build_from_hash(scaleValue: 0.5).scale_value
nil
```
Temporary Fix:

```ruby
module FixSwaggerTypes
  def self.included(base)
    base.class_eval do
      class << self
        alias _swagger_types swagger_types
        def swagger_types
          _swagger_types.merge(
            scale_value: :Float
          )
        end
      end
    end
  end
end

class DocuSign_eSign::SignHere
  include FixSwaggerTypes
end

class DocuSign_eSign::InitialHere
  include FixSwaggerTypes
end

```

**Comment by iagopiimenta** [comment]
This is not a question, it's a bug ;)

**Comment by LarryKlugerDS** [comment]
Hi @iagopiimenta ,
In the API itself, all values are currently sent as strings. Since the SDK is machine generated from the Swagger file, the SDK's arguments should be strings. 

Does it work if you supply a string value?

We agree that Booleans, Integers, Floats should be used in the API as appropriate instead of strings, and that enhancement is planned for the future. But they're all strings at this point.

Does

````
DocuSign_eSign::SignHere.new.build_from_hash(scaleValue: "0.5").scale_value
````
also return nil?

Thank you,
Larry
