### ISSUE TITLE
JSON version of version 2.0

### ISSUE THREAD

**Issue by abuisman** [docusign/docusign-ruby-client#22]
In PR https://github.com/docusign/docusign-ruby-client/pull/14 the JSON version is bumped to 2.1, however, in the latest release of this gem (2.0.0) we see JSON 1.8. Is there an issue with regards to using json 2.1? We'd rather use a more recent version of json.

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed internal bug reports. (See labels.)

**Comment by dantelljohann** [comment]
Would it be possible to get an update on this request? I am trying to integrate with DocuSign but we have another dependency that requires JSON 2.1

**Comment by LarryKlugerDS** [comment]
Both issues are still in our plan but are awaiting resources. Unfortunately I don't have a planned date at this time.

**Comment by LarryKlugerDS** [comment]
Good news, this issue has been fixed with the 3.0.0.rc.1 release of the SDK and [gem](https://rubygems.org/gems/docusign_esign/versions/3.0.0.rc1). The source is available as branch [ngopala/v2.1-19.2.02](https://github.com/docusign/docusign-ruby-client/tree/ngopala/v2.1-19.2.02). 

It will be released to master and the gem will be updated in the next week.

Please comment on this issue if you spot any issues with the RC (release candidate) or the forthcoming release.

Thanks,
Larry
