### ISSUE TITLE
Support for DocuSign API 2.1

### ISSUE THREAD

**Issue by vcsizmadia** [docusign/docusign-ruby-client#23]
We would like to take advantage of some of the new filtering capabilities available in version 2.1 of the API. When are you guys planning on getting the API updates into the gem?

**Comment by LarryKlugerDS** [comment]
The API v2.1 Ruby SDK release is currently scheduled for this August.
________________________________

**Comment by LarryKlugerDS** [comment]
Unfortunately we didn't make the August plan. I'm checking on the current schedule. Internal ticket DCM-3546

**Comment by LarryKlugerDS** [comment]
Good news, this issue has been fixed with the 3.0.0.rc.1 release of the SDK and [gem](https://rubygems.org/gems/docusign_esign/versions/3.0.0.rc1). The source is available as branch [ngopala/v2.1-19.2.02](https://github.com/docusign/docusign-ruby-client/tree/ngopala/v2.1-19.2.02). 

It will be released to master and the gem will be updated in the next week.

Please comment on this issue if you spot any issues with the RC (release candidate) or the forthcoming release.

Thanks,
Larry
